<a href="https://colab.research.google.com/github/ealexbarros/plotly_and_dash_course/blob/master/numpy_crash_course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Crash Course

In [0]:
import numpy as np

In [2]:
mylist = [1,2,3,4,5]
np.array(mylist)

array([1, 2, 3, 4, 5])

In [3]:
type(mylist)

list

In [4]:
type(np.array(mylist))

numpy.ndarray

In [0]:
arr_numpy = np.array(mylist)

In [6]:
type(arr_numpy)

numpy.ndarray

In [7]:
arr_generate = np.arange(0,10)
arr_generate

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr_generate_step = np.arange(0,10,2)
arr_generate_step

array([0, 2, 4, 6, 8])

In [9]:
np.zeros((1,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
type(1)

int

In [12]:
type(1.)

float

In [13]:
np.random.randint(0,100,(5,5))

array([[79, 92, 99, 87, 65],
       [29, 27,  1, 12, 60],
       [27, 43, 28, 64, 14],
       [72, 28, 88, 10, 47],
       [14, 68, 86, 15, 31]])

In [14]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [0]:
np.random.seed(101)


In [16]:
np.random.randint(1,100,10)

array([96, 12, 82, 71, 64, 88, 76, 10, 78, 41])

In [17]:
np.random.randint(0,100,(5,5))

array([[ 4, 63, 40, 60, 92],
       [64,  5, 12, 93, 40],
       [49, 83,  8, 29, 59],
       [34, 44, 72, 19, 10],
       [76, 95, 87,  0, 73]])

In [18]:
arr_randint = np.random.randint(0,100,(5,5))
arr_randint.max()

99

In [19]:
arr_randint = np.random.randint(0,100,(5,5))
arr_randint.min()

2

In [20]:
arr_randint.mean()

39.96

In [21]:
arr_randint

array([[24, 36, 63, 19, 35],
       [30, 10, 60, 20, 27],
       [ 8, 86, 26, 87, 46],
       [47, 54, 86,  9, 45],
       [ 2, 18, 58, 92, 11]])

In [22]:
arr_randint.argmax()

23

In [23]:
arr_randint.argmin()

20

In [26]:
arr_randint.reshape(1,25)

array([[24, 36, 63, 19, 35, 30, 10, 60, 20, 27,  8, 86, 26, 87, 46, 47,
        54, 86,  9, 45,  2, 18, 58, 92, 11]])

In [0]:
arr_1 = np.random.randint(0,100,(1,20))

In [30]:
arr_1

array([[94, 35, 28,  3, 83, 84, 47, 14, 69, 60, 69, 51,  6, 88, 71, 68,
        23, 35, 79, 98]])

In [31]:
arr_1.reshape(2,10)

array([[94, 35, 28,  3, 83, 84, 47, 14, 69, 60],
       [69, 51,  6, 88, 71, 68, 23, 35, 79, 98]])

In [33]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [34]:
mat[4,3]

43

In [35]:
mat[:,2]

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [36]:
mat[2,:]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [37]:
mat > 40

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [38]:
mat[mat<40]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])