<a href="https://colab.research.google.com/github/ealexbarros/plotly_and_dash_course/blob/master/Pandas_crash_course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

In [0]:

data_url = "https://raw.githubusercontent.com/ealexbarros/plotly_and_dash_course/master/salaries.csv"
data_df = pd.read_csv(data_url)

In [3]:
data_df

Name  Salary  Age    Company
0      Alex   15000   29     Google
1  Fernanda   16000   31     Amazon
2    Alyssa   12000   38      Apple
3     Elton   13000   45  Microsoft

In [4]:
print(data_df["Salary"])

0    15000
1    16000
2    12000
3    13000
Name: Salary, dtype: int64


In [5]:
print(data_df[['Name','Salary']])

       Name  Salary
0      Alex   15000
1  Fernanda   16000
2    Alyssa   12000
3     Elton   13000


In [6]:
data_df["Salary"].min()

12000

In [7]:
data_df["Salary"].max()

16000

In [8]:
data_df["Salary"].mean()

14000.0

In [9]:
data_df['Age'] > 30

0    False
1     True
2     True
3     True
Name: Age, dtype: bool

In [10]:
filter = data_df['Age'] > 30
data_df[filter]

Name  Salary  Age    Company
1  Fernanda   16000   31     Amazon
2    Alyssa   12000   38      Apple
3     Elton   13000   45  Microsoft

In [11]:
data_df['Age'].unique()

array([29, 31, 38, 45])

In [12]:
data_df['Age'].nunique()

4

In [14]:
data_df.columns

Index(['Name', 'Salary', 'Age', 'Company'], dtype='object')

In [16]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
Name       4 non-null object
Salary     4 non-null int64
Age        4 non-null int64
Company    4 non-null object
dtypes: int64(2), object(2)
memory usage: 256.0+ bytes


In [17]:
data_df.describe()

Salary        Age
count      4.000000   4.000000
mean   14000.000000  35.750000
std     1825.741858   7.274384
min    12000.000000  29.000000
25%    12750.000000  30.500000
50%    14000.000000  34.500000
75%    15250.000000  39.750000
max    16000.000000  45.000000

In [18]:
data_df.index

RangeIndex(start=0, stop=4, step=1)

In [22]:
mat = np.arange(0,50).reshape(5,10)
print(mat)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [23]:
df = pd.DataFrame(data=mat)
print(df)

    0   1   2   3   4   5   6   7   8   9
0   0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19
2  20  21  22  23  24  25  26  27  28  29
3  30  31  32  33  34  35  36  37  38  39
4  40  41  42  43  44  45  46  47  48  49


In [25]:
mat2 = np.arange(0,10).reshape(5,2)
df2 = pd.DataFrame(data=mat2,columns=['A','B'])
print(df2)

   A  B
0  0  1
1  2  3
2  4  5
3  6  7
4  8  9
